[terminal.shell]
program = "/opt/homebrew/bin/fish"

[window]
startup_mode = "SimpleFullscreen"
decorations = "buttonless"
blur = true
opacity = 0.83
dynamic_padding = true

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
